[package]
name = "anthaathi-graphql-common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0"
serde_yaml = "0.8"
serde_derive = "1.0.137"

[dev-dependencies]
indoc = "1.0"
